name: Build

on:
  push:
    branches: [ main ]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: build
      run: |
        sudo apt update -y && apt install build-essential ninja-build git-all cmake python3 libicu-dev -y
        git clone https://github.com/facebook/hermes.git
        cmake -S hermes -B build -G Ninja
        cmake --build ./build
        cd hermes/android && ./gradlew

