name: Build

on:
  push:
    branches: [ main ]

jobs:
  build_site:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: build
      run: |
        sudo apt update -y && sudo apt install ninja-build cmake -y
        git clone https://github.com/ayroblu/hermes.git
        export HERMES_WS_DIR="$(pwd)"
        cmake -S hermes -B ./build
        cmake --build ./build --target hermesc
        # cmake -S hermes -B build -G Ninja
        # cmake --build ./build
        cd hermes/android && ./gradlew build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          build/bin
          build_android/outputs

